version: '3.8'

services:
  python-nft:
    build:
      context: .
      dockerfile: Dockerfile
    command: python nft-generator.py runserver 0.0.0.0:8000
    volumes:
      - spa_data:/home/app/webapp
    ports:
      - 8000:8000

volumes:
  spa_data: